server:
  port: ${PORT:9000}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "cards"
  profiles:
    active: '@spring.active.profile@'
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"  # enable and expose all management endpoint supported by the spring boot actuator
