build:
  version: "3.0"

accounts:
  message: "Welcome to Bank accounts related local APIs "
  contactDetails:
    name: "Akash - Developer"
    email: "akash@example.com"
  onCallSupport:
    - +8801XXXXXXXXX
    - +8801XXXXXXXX3