version: "1.2"

services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "akash9229/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      #test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      test: "curl --fail --silent localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "akash9229/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loan:
    image: "akash9229/loan:v1"
    container_name: loan-ms
    ports:
      - "8090:8090"
    environment:
      #      SPRING_APPLICATION_NAME: "loan"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "akash9229/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      #      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  akashNetwork:
    driver: "bridge"
