server:
  port: ${PORT:8090}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "cards"
  profiles:
    active: '@spring.active.profile@'
  config:
    import: "optional:configserver:http://localhost:8071"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    stream:
#      username: "guest"
#      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"  # enable and expose all management endpoint supported by the spring boot actuator
