spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          search-locations: "file:/home/akashbhuiyan/Learning/config" # configurattion from file services
        git:
          uri: "https://github.com/AkashBhuiyan/microservice-architecture-java-configs.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  #Refresh configurations at runtime using Spring Cloud Bus
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    stream:
#      username: "guest"
#      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"  # enable and expose all management endpoint supported by the spring boot actuator
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
encrypt:
  key: "COMPLEXKEYFORENCRYPTDYCRYPTITCANBEANYCOMPLEXTEXT" # it will encrypt and decrypt our properties

server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
