spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          search-locations: "file:/home/akash/Project/config" # configurattion from file services
        git:
          uri: "https://github.com/AkashBhuiyan/microservice-architecture-java-configs.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "COMPLEXKEYFORENCRYPTDYCRYPTITCANBEANYCOMPLEXTEXT" # it will encrypt and decrypt our properties

server:
  port: 8071
